# Rename this file to languages.toml to enable multilingual support
# Rename this file to _languages.toml to enable single language support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Xing Personal Page"
weight = 1

[zh-cn]
languageName = "Chinese"
languagedirection = "ltr"
title = "邢栋夏"
weight = 2
